In [2]:
import numpy as np

In [5]:
nums = np.array([1,3,5,7,9])
print (nums)

[1 3 5 7 9]


In [6]:
nums_plus_2=nums +2
print (nums_plus_2)

[ 3  5  7  9 11]


In [7]:
nums_times_3=nums * 3
print (nums_times_3)

[ 3  9 15 21 27]


In [8]:
print(np.sum(nums))
print(np.max(nums))
print(np.mean(nums))

25
9
5.0
