In [1]:
import numpy as np

In [2]:
nums = np.array([1, 3, 5, 7, 9])

In [3]:
print(nums)

[1 3 5 7 9]


In [5]:
nums2 =np.array(nums + 2)

In [6]:
print(nums2)

[ 3  5  7  9 11]


In [7]:
nums3 = np.array(nums2 * 3)

In [8]:
print(nums3)

[ 9 15 21 27 33]


In [11]:
total = np.sum(nums)
Maximum = np.max(nums)
Average = np.mean(nums)
print('Sum:', total)
print('MAximum VAlue:',Maximum)
print('Average:', Average)

Sum: 25
MAximum VAlue: 9
Average: 5.0
